In [ ]:
pip install torch torchvision torchaudio numpy pandas matplotlib


   ---------------------------------------- 0.0/4.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.5/4.3 MB 3.4 MB/s eta 0:00:02
   -------------------------------------- - 4.2/4.3 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 4.3/4.3 MB 10.9 MB/s  0:00:00

   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   ---------------------------------------- 0/2 [torchvision]
   -----------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [ ]:
import torch  # CLASS METHOD

x = torch.tensor([1,2,3,4])

print(x)

tensor([1, 2, 3, 4])


In [ ]:
import torch

x = torch.tensor([
    [1,2],
    [3,4]
])

print(x) # 4

tensor([[1, 2],
        [3, 4]])


In [3]:
import torch

a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a + b)

tensor([5, 7, 9])


In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cpu


In [5]:
import torch

a = torch.tensor([2,3,4])
b = torch.tensor([5,6,7])

print(a * b)

tensor([10, 18, 28])


In [6]:
import torch

a = torch.tensor([10,20,30])
b = torch.tensor([2,5,10])

print(a / b)

tensor([5., 4., 3.])


In [7]:
import torch

a = torch.tensor([1,2,3])

print(a + 5)

tensor([6, 7, 8])


In [8]:
import torch

a = torch.zeros(3)

print(a)

tensor([0., 0., 0.])


In [9]:
import torch

a = torch.ones(4)

print(a)

tensor([1., 1., 1., 1.])


In [10]:
import torch

a = torch.rand(3)

print(a)

tensor([0.4698, 0.3280, 0.4638])


In [ ]:
import torch

a = torch.tensor([[1,2,3],
                  [4,5,6]])

print(a.shape) # 2* 3

torch.Size([2, 3])


In [ ]:
import torch

a = torch.tensor([[1,2,3],
                  [4,5,6]])

print(a[0][1]) #  0 1 00 02   

# 9  2 ,2

       0  1  2

    0
    1
    2   

tensor(2)


In [1]:
import torch

a = torch.tensor([1,2,3,4,5,6])

b = a.view(2,3)  # convert 1D to 2D   1 darray conver 2d 

print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
import torch

a = torch.tensor([1,2,3]) #tourch 

b = a.numpy() # tensor - tourch //numpy 

print(b) #numpy //method  

[1 2 3]


In [ ]:
import torch

a = torch.tensor([[1,2],[3,4]])

 1,2       5,6
 3,4       7,8

b = torch.tensor([[5,6],[7,8]])  # 5 + 14   

c = torch.matmul(a,b)

print(c) # (a rows × b columns)

tensor([[19, 22],
        [43, 50]])


In [ ]:
import torch

a = torch.tensor([[1,2,3],
                  [4,5,6]]) # 2* 3  3* 2 

print(a.T)  #2×3 → 3×2

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [8]:
import torch

a = torch.tensor([1,2,3,4,5])

print(torch.mean(a.float()))
print(torch.sum(a))

tensor(3.)
tensor(15)


In [9]:
import torch

a = torch.tensor([10,25,5,30])

print(torch.max(a))
print(torch.min(a))

tensor(30)
tensor(5)


In [ ]:
import torch

a = torch.tensor([[1,2],
                  [3,4]])

b = torch.flatten(a) # 2 d convert  1d

print(b) #Multi dimension to 1D 

In [ ]:
import torch

x = torch.tensor(2.0, requires_grad=True)

  # gradient - best fit line //slop 

#dy/dx = 2x + 3
#x = 2
#gradient = 7
#y=x2+3x+1

y = x**2 + 3*x + 1

y.backward() # forward backward loss fucntion 

print(x.grad)

tensor(7.)


In [2]:
import torch

a = torch.tensor([1,2,3])

print(a.dtype)

torch.int64


In [ ]:
a = a.float()  # type casting  // lower vaule datatype - highe dat convert 
 
 #higher data value - lower    8     fo 4

print(a.dtype)

torch.float32


In [ ]:
import torch
 
a = torch.arange(0,10)  #view  flatern filtering  array 

print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [5]:
import torch

a = torch.tensor([1,2,3])
b = torch.tensor([2,2,2])

print(a > b)

tensor([False, False,  True])


In [15]:
import torch

a = torch.tensor([1,5,10,15,20])

b = torch.clamp(a, min=3, max=10) #value 

print(b)

tensor([ 3,  5, 10, 10, 10])


In [7]:
import torch

a = torch.tensor([1,2,2,3,3,4])

print(torch.unique(a))

tensor([1, 2, 3, 4])


In [ ]:
import torch

a = torch.eye(3) #  1  0   1  0 1 0 1

print(a)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [9]:
import torch

a = torch.full((3,3),5)

print(a)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
import torch

a = torch.tensor([10,25,5,30])

print(torch.argmax(a)) #index based 

tensor(3)


In [11]:
import torch

a = torch.tensor([5,1,8,3])

b = torch.sort(a)

print(b)

torch.return_types.sort(
values=tensor([1, 3, 5, 8]),
indices=tensor([1, 3, 0, 2]))


In [12]:
import torch

a = torch.tensor([-5,-2,3])

print(torch.abs(a))

tensor([5, 2, 3])


In [13]:
import torch

a = torch.tensor([4,9,16])

print(torch.sqrt(a))

tensor([2., 3., 4.])


In [14]:
import torch

a = torch.tensor([2,3,4])

print(torch.pow(a,2))

tensor([ 4,  9, 16])


In [ ]:
import torch

#cuda -  gpu availble // calulation - cpu migrate cpu - gpu 
#

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

a = torch.tensor([1,2,3])

a = a.to(device)    #tensor cpu to gpu

print(a)

tensor([1, 2, 3])


In [ ]:
import torch


# ann - deep learning  photon -20-30 cycle 
#gatesfoundation 10-20 
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

a = torch.tensor([1,2,3]).to(device)
b = torch.tensor([4,5,6]).to(device)   # tensor operation in gpu

c = a + b
#n8n
print(c)

tensor([5, 7, 9])


In [3]:
import torch

a = torch.randint(0,10,(3,3))

print(a)

tensor([[8, 3, 1],
        [8, 4, 6],
        [4, 7, 6]])


In [ ]:
import torch

a = torch.tensor([1,2,3])

b = a.clone()  #deep copy and shalow

print(b)

tensor([1, 2, 3])


In [ ]:
import torch

a = torch.tensor([[1,2,3],
                  [4,5,6]])

print(torch.numel(a))  #find total element

In [5]:
import torch

x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])

y = torch.sigmoid(x)

print(y)

tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])
